let bookTitle: string = "TypeScriptBasics"
let libraryName: string = "My Library"
let numberOfBooks: number = 340
let isLibraryOpen: boolean = true
let titulo: string = "En busca del tiempo perdido"
let autor: string = "Marcel Proust"
let genero: string = "Ficción"
let idioma: string = "Español"
let precio: number = 89900
let formato: string = "Tapa blanda"
let isbn: string = "9780143039938"
let descripcion: string = "Una novela que narra las experiencias y recuerdos del narrador."
let estado: string = "Nuevo"
let ubicacion: string = "Pasillo 7, Estante 2"
let fecha_publicacion: string = "1913"
let editorial: string = "Laguna Libros"
let paginas:number = 4211
let dimensiones: string = "15 x 6 x 23 cm"
let peso: string = "2.4 kg"
let disponible: boolean = true